dist: xenial
language: python
python:
    - '3.5'
    - '3.6'
    - '3.7'
install:
    - 'pip install -r requirements.txt'
script:
    - 'pytest mlaction'
deploy:
    provider: pypi
    user: iosdevlog
    'true': {python: 3.7, tags: true, branch: master}
    skip_cleanup: true
    distributions: 'sdist bdist_wheel'
    password: {secure: QDojsiek5bQUhzi6G9k1jiVgwAo0KCD5jtKEyodYjwr3BzxGwtN/5ifGo145JagSY8lCX3JS0jkLLKQb64EW/vTLyQKkl1NqfWYdYZ1RQ26yYvfsy4s2ukDYYN5uTFLuMiqNOJmKxcGHOYxU5FEVwBiMw3D4x9MAdg+f9J8rvX7T5CiHCXIFD/NfyeiJTACB+7frJkf7L2dGocRfGedr9OcxA9SrXzAlRfFRA6V2NnBOG1uDA65ouuqhBCnAsfyx6Uw5SPws1ljprMySylMxZ85MGgEK0mq6ol6g958mvMPXmxmrHDtrdWVBuB5zTu3v6QoQay8akP3GL9QKiw36ykVlZ/jUw+hQhInBKT01lfD7ViJXW7RZRk+LJSLqwAiOv7WpP6RLyux6Rof5+rnaVh62wiyY4Jo+hPGeqT9v9L7TaLAAVgc5u7a61v1vMOsBFK1PrYNk16FmfRj3zFd1MlBDfztHlmlWMDIC4I9Jc6QxVI+wEntM+cjFUwymXR2OnjMRFvNfWLmrTwwQSjVR1hRPv4EllUojxM7cjBrOgp3L6zjVt6UfhWY0kyQ5d4eyV4mMQaL8rbcfbKVBbb1A94THzrxsAd21heGof4RCkIrAd0pRMNlAkYU/ZSYfRiyxISh8d7YlMa2ZN7OJ1VC+yCTetwtUi8T5Go3hZsFPFUY=}

